"""
@author: TYZ
compute average word length
usage : input the target number to be generated by {1, 3, 9, 27}. Return the result
        of generation.
"""


def get_power_of3(target):
    """
    :param target: target number generating from {1, 3, 9, 27}
    :return: a 4 element list containing each argument's time

    Function design : using the math tricks to separate the numbers
                      into different categories.
    """
    assert(0 <= target <= 40)
    result = [0, 0, 0, 0]
    while target:
        if target >= 14:
            target -= 27
            result[3] = 1
        elif target >= 5:
            target -= 9
            result[2] = 1
        elif target >= 2:
            target -= 3
            result[1] = 1
        elif target == 1:
            result[0] = 1
            target -= 1
        elif target <= -5:
            target += 9
            result[2] = -1
        elif target <= -2:
            target += 3
            result[1] = -1
        elif target == -1:
            target += 1
            result[0] = -1

    return result

